#' Data upload
#'
#' Safely uploads data to be processed in DIETCOST software.
#' @param filepath The filepath in which the dataset, in .xlsx format, is saved.
#' @param sheet The sheet of the .xlsx to be read.
#' @return The dataframe generated by the file which was read.
#' @examples 
#' df <- upload_data('C:/Users/username/Downloads/dataset.xlsx', 'foods');
#' @export
upload_data <- function(filepath, sheet){
  df<- tryCatch(
    expr = {read_excel(filepath, sheet)},
    error = function(e){
      print('Upload failed!')
      stop(e)}
  )
  return(df)
}